# Generated by Django 3.0.2 on 2020-05-06 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20190812_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='applyby',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(default='Work from home', max_length=300),
        ),
        migrations.AddField(
            model_name='intern',
            name='sdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='intern',
            name='stip',
            field=models.IntegerField(default=0),
        ),
    ]
