# Generated by Django 3.0.2 on 2020-05-06 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200506_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup1',
            name='phone_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
